public class opportunityTriggerHandler15 
{
    public static void beforeInsertHandler(List<Opportunity> newOpps)
    {
        // future before-insert logic
    }
    public static void beforeUpdateHandler(List<Opportunity> newOpps,Map<Id, Opportunity> oldOppMap)
    {
        // future before-update logic
    }
    public static void afterUpdateHandler(List<Opportunity> newOpps,Map<Id, Opportunity> oldOppMap)
    {
        // future after-update logic
    }
}